# Generated by Django 2.2.1 on 2019-06-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20190601_1523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Board',
        ),
    ]
